theme: jekyll-theme-hacker
title: Stock_God
description: You must read this page if you want to become a stock god.
show_downloads: true
github:
  zip_url: https://lepg5487.github.io/Stock_God/
  tar_url: https://lepg5487.github.io/Stock_God/experience

# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
