theme: jekyll-theme-hacker
title: Stock_God
description: You must read this page if you want to become a stock god. 
show_downloads: true
github:
  zip_url: https://lepg5487.github.io/Stock_God/
  tar_url: https://lepg5487.github.io/Stock_God/experience
  video_url: https://lepg5487.github.io/Stock_God/video
  NovelAI_url: https://lepg5487.github.io/Stock_God/NovelAI
  ChatGPT_url: https://lepg5487.github.io/Stock_God/ChatGPT
  
  
#  repository_url: https://github.com/lepg5487/Stock_God/blob/master/index.md

# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
